
development:
  adapter: postgresql
  encoding: unicode
  database: dbWebKnow
  pool: 5
  username: root
  password: sa
  host: localhost
  port: 5434

# test:
  # adapter: postgresql
  # encoding: unicode
  # database: dbWebLearn_test
  # pool: 5
  # username: weblearn
  # password:

production:
  adapter: postgresql
  encoding: unicode
  database: dbWebKnow
  pool: 5
  username: root
  password: sa
  host: localhost
  port: 5434
  